## docker-compose.yml
```yaml
version: "3.8"
services:
api:
build: .
ports:
- "8000:8000"
env_file: .env
depends_on:
- postgres
- qdrant
volumes:
- ./app:/app
qdrant:
image: qdrant/qdrant:latest
ports:
- "6333:6333"
volumes:
- qdrant_storage:/qdrant/storage
postgres:
image: postgres:15
environment:
POSTGRES_USER: pguser
POSTGRES_PASSWORD: pgpass
POSTGRES_DB: greener
ports:
- "5432:5432"
volumes:
- pgdata:/var/lib/postgresql/data
2
volumes:
qdrant_storage:
pgdata:
